# -*- coding: utf-8 -*-
betwords = [
    "bet",
    "odds",
    "chances",
    "wager",
    "gamble",
    "probability",
    "likelihood",
]

idcall = [
    "I'd call the odds ",
    "The odds are ",
    "Chances might be ",
]

foragainst = [
    "of ",
    "for ",
    "against ",
]

bettings = [
    "Across the board",
    "Act of God",
    "As good luck would have it",
    "Back the field",
    "Bet your bottom dollar",
    "Bread always falls buttered side down",
    "Copper-bottomed",
    "Dead ringer",
    "Don't count your chickens before they are hatched",
    "Draw a blank",
    "Eeny, meeny, miny, mo",
    "Hedge your bets",
    "Second-guess",
    "Take potluck",
    "Third time lucky",
    "Turn the tables",
]

adjs = ["able",
    "acid",
    "angry",
    "automatic",
    "awake",
    "bad",
    "beautiful",
    "bent",
    "bitter",
    "black",
    "blue",
    "boiling",
    "bright",
    "broken",
    "brown",
    "certain",
    "cheap",
    "chemical",
    "chief",
    "clean",
    "clear",
    "cold",
    "common",
    "complete",
    "complex",
    "conscious",
    "cruel",
    "cut",
    "dark",
    "dead",
    "dear",
    "deep",
    "delicate",
    "dependent",
    "different",
    "dirty",
    "dry",
    "early",
    "elastic",
    "electric",
    "equal",
    "false",
    "fat",
    "feeble",
    "female",
    "fertile",
    "first",
    "fixed",
    "flat",
    "free",
    "frequent",
    "full",
    "future",
    "general",
    "good",
    "gray",
    "great",
    "green",
    "hanging",
    "happy",
    "hard",
    "healthy",
    "high",
    "hollow",
    "ill",
    "important",
    "kind",
    "last",
    "late",
    "left",
    "like",
    "living",
    "long",
    "loose",
    "loud",
    "low",
    "male",
    "married",
    "material",
    "medical",
    "military",
    "mixed",
    "narrow",
    "natural",
    "necessary",
    "new",
    "normal",
    "old",
    "open",
    "opposite",
    "parallel",
    "past",
    "physical",
    "political",
    "poor",
    "possible",
    "present",
    "private",
    "public",
    "quick",
    "quiet",
    "ready",
    "red",
    "regular",
    "responsible",
    "right",
    "rough",
    "round",
    "sad",
    "safe",
    "same",
    "second",
    "secret",
    "separate",
    "serious",
    "sharp",
    "short",
    "shut",
    "simple",
    "slow",
    "small",
    "smooth",
    "soft",
    "solid",
    "special",
    "sticky",
    "stiff",
    "straight",
    "strange",
    "strong",
    "sudden",
    "sweet",
    "tall",
    "thick",
    "thin",
    "tight",
    "tired",
    "true",
    "violent",
    "waiting",
    "warm",
    "wet",
    "white",
    "wide",
    "wise",
    "wrong",
    "yellow",
    "young",
    ]

obliques = [
    "Turn it over.",
    "Switch the axes.",
    "Think about color.",
    "Make it black and white.",
    "Use the tangents.",
    "Move across the room.",
    "Restart.",
    "Make it ridiculous.",
    "Stop making sense.",
    "Emphasize the side effects.",
    "Turn it into a game.",
    "More semicolons.",
    "Apply the Sieve of Eratosthenes.",
    "Try faking it.",
    "State the problem in words as clearly as possible.",
    "Only one element of each kind.",
    "What would your closest friend do?",
    "What to increase? What to reduce?",
    "Are there sections? Consider transitions.",
    "Don't think. Do.",
    "As a good friend of mine used to say... burrito burrito burrito burrito FALCON burrito!",
    "But, does it float?",
    "Remove half.",
    "Abandon normal instruments.",
    "Accept advice.",
    "A line has two sides.",
    "Balance the consistency principle with the inconsistency principle.",
    "Breathe more deeply.",
    "Bridges: -build, -burn.",
    "Consider different fading systems.",
    "Courage!",
    "Cut a vital connection.",
    "Decorate, decorate.",
    "Define an area as 'safe' and use it as an anchor.",
    "Destroy the most important thing.",
    "Discard an axiom.",
    "Disconnect from desire.",
    "Discover the recipes you are using and abandon them.",
    "Distorting time.",
    "Don't be afraid of things because they're easy to do.",
    "Don't be frightened of cliches.",
    "Don't be frightened to display your talents.",
    "Don't stress one thing more than another.",
    "Do something boring.",
    "Do the washing up.",
    "Do the words need changing?",
    "Do we need holes?",
    "Emphasize differences.",
    "Emphasize repetitions.",
    "Emphasize the flaws.",
    "Go slowly all the way round the outside.",
    "Honor thy error as a hidden intention.",
    "How would you have done it?",
    "Humanize something free of error.",
    "Infinitesimal gradations.",
    "Into the impossible.",
    "Is it finished?",
    "Is there something missing?",
    "Just carry on.",
    "Left channel, right channel, centre channel.",
    "Look at a very small object, look at its centre.",
    "Look at the order in which you do things.",
    "Look closely at the most embarrassing details and amplify them.",
    "Make a blank valuable by putting it in an exquisite frame.",
    ("Make an exhaustive list of everything you might do and do the last "
        "thing on the list."),
    "Make a sudden, destructive, unpredictable action; incorporate.",
    "Only one element of each kind.",
    "Remember those quiet evenings.",
    "Remove ambiguities and convert to specifics.",
    "Remove specifics and convert to ambiguities.",
    "Repetition is a form of change.",
    "Reverse.",
    "Simple subtraction.",
    "Spectrum analysis.",
    "Take a break.",
    "Take away the elements in order of apparent non-importance.",
    "Tidy up.",
    "Turn it upside down.",
    "Twist the spine.",
    "Use an old idea.",
    "Use an unacceptable color.",
    "Water.",
    "What are you really thinking about just now? Incorporate.",
    "What is the reality of the situation?",
    "What mistakes did you make last time?",
    "What wouldn't you do?",
    "Work at a different speed.",
    "Take a walk.",
    "Take a shower.",
    "Look to Nature.",
    "Talk it through with a friend.",
    "Who's your audience?",
    "Forget the money, make it cool."
]


nouns = ["angle",
     "ant",
     "apple",
     "arch",
     "arm",
     "army",
     "baby",
     "bag",
     "ball",
     "band",
     "basin",
     "basket",
     "bath",
     "bed",
     "bee",
     "bell",
     "berry",
     "bird",
     "blade",
     "board",
     "boat",
     "bone",
     "book",
     "boot",
     "bottle",
     "box",
     "boy",
     "brain",
     "brake",
     "branch",
     "brick",
     "bridge",
     "brush",
     "bucket",
     "bulb",
     "button",
     "cake",
     "camera",
     "card",
     "carriage",
     "cart",
     "cat",
     "chain",
     "cheese",
     "chess",
     "chin",
     "church",
     "circle",
     "clock",
     "cloud",
     "coat",
     "collar",
     "comb",
     "cord",
     "cow",
     "cup",
     "curtain",
     "cushion",
     "dog",
     "door",
     "drain",
     "drawer",
     "dress",
     "drop",
     "ear",
     "egg",
     "engine",
     "eye",
     "face",
     "farm",
     "feather",
     "finger",
     "fish",
     "flag",
     "floor",
     "fly",
     "foot",
     "fork",
     "fowl",
     "frame",
     "garden",
     "girl",
     "glove",
     "goat",
     "gun",
     "hair",
     "hammer",
     "hand",
     "hat",
     "head",
     "heart",
     "hook",
     "horn",
     "horse",
     "hospital",
     "house",
     "island",
     "jewel",
     "kettle",
     "key",
     "knee",
     "knife",
     "knot",
     "leaf",
     "leg",
     "library",
     "line",
     "lip",
     "lock",
     "map",
     "match",
     "monkey",
     "moon",
     "mouth",
     "muscle",
     "nail",
     "neck",
     "needle",
     "nerve",
     "net",
     "nose",
     "nut",
     "office",
     "orange",
     "oven",
     "parcel",
     "pen",
     "pencil",
     "picture",
     "pig",
     "pin",
     "pipe",
     "plane",
     "plate",
     "plough",
     "pocket",
     "pot",
     "potato",
     "prison",
     "pump",
     "rail",
     "rat",
     "receipt",
     "ring",
     "rod",
     "roof",
     "root",
     "sail",
     "school",
     "scissors",
     "screw",
     "seed",
     "sheep",
     "shelf",
     "ship",
     "shirt",
     "shoe",
     "skin",
     "skirt",
     "snake",
     "sock",
     "spade",
     "sponge",
     "spoon",
     "spring",
     "square",
     "stamp",
     "star",
     "station",
     "stem",
     "stick",
     "stocking",
     "stomach",
     "store",
     "street",
     "sun",
     "table",
     "tail",
     "thread",
     "throat",
     "thumb",
     "ticket",
     "toe",
     "tongue",
     "tooth",
     "town",
     "train",
     "tray",
     "tree",
     "trousers",
     "umbrella",
     "wall",
     "watch",
     "wheel",
     "whip",
     "whistle",
     "window",
     "wing",
     "wire",
     "worm",
]

canstarts = [
    "Yes, you'll need ",
    "Yes, but watch out for ",
    "Maybe if you had ",
    "Nope, there's too much of ",
    "Never! Insufficient ",
    "Perhaps try with ",
]

affirmatives = [
    ' do ',
    'Heck yes!',
    'I think... Yes.',
    'It could be.',
    'Maybe.',
    'Possibly.',
    'Without a doubt.',
    'Yes.',
    'does the pope... er, is this the right channel?'
    'mhmm',
    'right',
    'sure',
    'yeah',
    'yes',
    'you said it',
    'yup',
    'yus',
]

negatories = [
    "don't",
    'no',
    'nope',
    'nerp',
    'never',
    'nah',
    'NEVAR',
    'Nope.',
    'No.',
    'Eww.',
    'No. No, no way',
    'That would be negatory.',
    'Why would anyone?',
]


responses = [
    ('Yes.', 'eq'),
    ('How should I know?', 'eq'),
    ('Try asking a human', 'eq/10'),
    ('Eww.', 'eq/4'),
    ('You\'d just do the opposite of whatever I tell you', 'eq/50'),
    ('No.', 'eq'),
    ('Wat?!', 'eq/50'),
    ('Why would anyone?', 'eq/50'),
    ('Nope.', 'eq'),
    ('Maybe.', 'eq'),
    ('Possibly.', 'eq'),
    ('It could be.', 'eq'),
    ("No. No, I don't think so.", 'eq/2'),
    ('Without a doubt.', 'eq/2'),
    ('I think... Yes.', 'eq/2'),
    ('Heck yes!', 'eq/10'),
    ('Maybe. Possibly. It could be.', 'eq/20'),
    ('Ask again later.', 'eq/30'),
    ("I don't know.", 'eq/3'),
    ("I'm sorry, I was thinking of bananas", 'eq/100'),
    ]
